import { useEffect,useRef,useState } from 'react';
import toast from 'react-hot-toast';
import { Award,Clock,Play,CheckCircle2,Eye,ChevronLeft,ChevronRight } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { supabase } from '../../lib/supabase';
import DashboardLayout from '../../layouts/DashboardLayout';
export default function CandidateAssessments(){
 const{user}=useAuth();const[templates,setTemplates]=useState([]),[results,setResults]=useState([]),[activeRun,setActiveRun]=useState(null),[questions,setQuestions]=useState([]),[answers,setAnswers]=useState({}),[current,setCurrent]=useState(0),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false);const timerRef=useRef(null),flagsRef=useRef([]);
 const load=async()=>{const[{data:t},{data:r}]=await Promise.all([supabase.from('assessment_templates').select('*').eq('is_active',true),supabase.from('assessment_results').select('*,assessment_templates(title,role_category,passing_score)').eq('candidate_id',user.id).order('created_at',{ascending:false})]);setTemplates(t||[]);setResults(r||[]);setLoading(false)};useEffect(()=>{if(user)load()},[user]);useEffect(()=>()=>clearInterval(timerRef.current),[]);
 useEffect(()=>{const h=()=>{if(activeRun&&document.hidden)flagsRef.current.push({type:'tab_switch',at:new Date().toISOString()})};document.addEventListener('visibilitychange',h);return()=>document.removeEventListener('visibilitychange',h)},[activeRun]);
 const finish=async(run)=>{if(!run||submitting)return;setSubmitting(true);clearInterval(timerRef.current);const payload=questions.map(q=>({question_id:q.id,selected_option:answers[q.id]??null}));const{data,error}=await supabase.rpc('submit_assessment',{p_result_id:run.resultId,p_answers:payload,p_flags:flagsRef.current});setSubmitting(false);if(error){toast.error(error.message);return;}const out=Array.isArray(data)?data[0]:data;setActiveRun(null);setQuestions([]);setAnswers({});setCurrent(0);toast.success(`Assessment submitted — score: ${out?.score??'—'}`);load()};
 const start=async(t)=>{const{data:rid,error}=await supabase.rpc('start_assessment',{p_template_id:t.id});if(error){toast.error(error.message);return;}const{data:qs,error:qErr}=await supabase.rpc('get_assessment_questions',{p_result_id:rid});if(qErr){toast.error(qErr.message);return;}if(!qs?.length){toast.error('No questions are available yet.');return;}flagsRef.current=[];setQuestions(qs);setAnswers({});setCurrent(0);setSubmitting(false);setActiveRun({resultId:rid,template:t,secondsLeft:t.duration_minutes*60});timerRef.current=setInterval(()=>setActiveRun(prev=>{if(!prev)return prev;if(prev.secondsLeft<=1){finish(prev);return prev}return{...prev,secondsLeft:prev.secondsLeft-1}}),1000)};
 if(activeRun){const q=questions[current];const mins=Math.floor(activeRun.secondsLeft/60),secs=activeRun.secondsLeft%60;return <DashboardLayout role="candidate"><div className="card mx-auto max-w-3xl"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="font-display text-xl font-bold">{activeRun.template.title}</h1><div className="text-sm text-white/40">Question {current+1} of {questions.length}</div></div><div className="rounded-full border border-accent-500/30 px-4 py-2 font-mono text-lg text-accent-300">{mins}:{secs.toString().padStart(2,'0')}</div></div><div className="mt-6"><div className="mb-4 text-lg font-medium">{q?.prompt}</div><div className="space-y-3">{(q?.options||[]).map((o,i)=><label key={i} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${answers[q.id]===i?'border-accent-500/60 bg-accent-500/10':'border-white/[0.08]'}`}><input type="radio" checked={answers[q.id]===i} onChange={()=>setAnswers(a=>({...a,[q.id]:i}))}/><span className="text-sm">{o}</span></label>)}</div></div><div className="mt-6 flex items-center justify-between border-t border-white/[0.06] pt-4"><button className="btn-secondary disabled:opacity-30" disabled={current===0} onClick={()=>setCurrent(n=>Math.max(0,n-1))}><ChevronLeft size={15}/>Previous</button>{current<questions.length-1?<button className="btn-primary" onClick={()=>setCurrent(n=>Math.min(questions.length-1,n+1))}>Next<ChevronRight size={15}/></button>:<button className="btn-primary" disabled={submitting} onClick={()=>finish(activeRun)}>{submitting?'Submitting…':'Submit Assessment'}</button>}</div><p className="mt-4 text-xs text-white/35">Tab switches are flagged for review only and never determine pass/fail.</p></div></DashboardLayout>}
 return <DashboardLayout role="candidate"><h1 className="mb-1 font-display text-2xl font-bold">Assessments</h1><p className="mb-6 text-white/50">Role-based assessments with real question scoring.</p><h2 className="mb-3 text-lg font-semibold">Available</h2>{loading?<div className="skeleton h-32"/>:<div className="mb-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{templates.map(t=><div key={t.id} className="card"><div className="mb-2 flex items-center gap-2"><Award size={16} className="text-accent-400"/><span className="text-xs uppercase text-white/40">{t.role_category}</span></div><div className="font-medium">{t.title}</div><p className="mt-1 text-xs text-white/50">{t.description}</p><div className="mt-3 text-xs text-white/40"><Clock size={12} className="mr-1 inline"/>{t.duration_minutes} min · {t.question_count} questions</div><button onClick={()=>start(t)} className="btn-primary mt-4 w-full !py-2 text-sm"><Play size={14}/>Start</button></div>)}{templates.length===0&&<p className="text-sm text-white/40">No assessments published yet.</p>}</div>}<h2 className="mb-3 text-lg font-semibold">Your Results</h2><div className="card">{results.length===0?<p className="py-8 text-center text-sm text-white/40">No assessments completed yet.</p>:<div className="divide-y divide-white/[0.06]">{results.map(r=><div key={r.id} className="flex items-center justify-between py-3"><div><div className="text-sm font-medium">{r.assessment_templates?.title}</div><div className="text-xs text-white/40">{r.status==='completed'?`Completed ${new Date(r.completed_at).toLocaleDateString()}`:r.status}</div></div><div className="flex items-center gap-2">{r.status==='completed'&&<span className="flex items-center gap-1 text-sm text-accent-400"><CheckCircle2 size={14}/>{r.score}</span>}{r.proctoring_flags?.length>0&&<span className="flex items-center gap-1 text-xs text-yellow-400"><Eye size={12}/>{r.proctoring_flags.length}</span>}</div></div>)}</div>}</div></DashboardLayout>;
}
